# Generated by Django 3.2.17 on 2023-05-05 13:55

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of the store')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={}, verbose_name='Location')),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map', verbose_name='Address')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('thumbnail', models.ImageField(default='default.png', upload_to='events/%Y/%M/', verbose_name='Logo')),
                ('minor', models.BooleanField(default=False)),
                ('framing_device', models.BooleanField(default=False)),
                ('camera_man', models.BooleanField(default=False)),
                ('body_protection', models.BooleanField(default=False)),
                ('authorization', models.FileField(blank=True, null=True, upload_to='events/authorization/%Y/%M/', verbose_name='authorization')),
                ('level', models.CharField(blank=True, choices=[('1', 'Professional'), ('2', 'Beginner')], default='2', max_length=5, verbose_name='Choose the level :')),
                ('helmet', models.BooleanField(default=False)),
                ('safety_vest', models.BooleanField(default=False)),
                ('bicycle_pump', models.BooleanField(default=False)),
                ('moto_type', models.CharField(blank=True, choices=[('1', 'Electric'), ('2', 'Fatbike'), ('3', 'Mountain'), ('4', 'Gravel'), ('5', 'Hybrid'), ('6', 'Urban')], default='6', max_length=5, verbose_name='Choose a type of bicycle:')),
                ('hiking_type', models.CharField(blank=True, choices=[('1', 'The Stroll'), ('2', 'Long hike and trekkin'), ('3', 'Technical hiking and mountaineering')], default='1', max_length=5, verbose_name='Choose a type of hiking:')),
                ('good_shoes', models.BooleanField(default=False, verbose_name='Good shoes')),
                ('walking_stick', models.BooleanField(default=False, verbose_name='Walking stick')),
                ('tent', models.BooleanField(default=False, verbose_name='Tent')),
                ('transport', models.BooleanField(default=False, verbose_name='Transport')),
                ('anti_slip_shoes', models.BooleanField(default=False, verbose_name='Anti slip shoes')),
                ('snow_stick', models.BooleanField(default=False, verbose_name='Snow stick')),
                ('warm_and_weatherproof_clothing', models.BooleanField(default=False, verbose_name='Warm and weatherproof clothing')),
                ('medical_certificate', models.ImageField(blank=True, null=True, upload_to='events/certificate/%Y/%M/', verbose_name='Medical certificate')),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
