# Generated by Django 3.2.17 on 2023-05-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bicycle_pump',
            field=models.BooleanField(default=False, verbose_name='Bicycle pump'),
        ),
        migrations.AlterField(
            model_name='event',
            name='body_protection',
            field=models.BooleanField(default=False, verbose_name='Body protection'),
        ),
        migrations.AlterField(
            model_name='event',
            name='camera_man',
            field=models.BooleanField(default=False, verbose_name='Camera man'),
        ),
        migrations.AlterField(
            model_name='event',
            name='framing_device',
            field=models.BooleanField(default=False, verbose_name='Framing device'),
        ),
        migrations.AlterField(
            model_name='event',
            name='helmet',
            field=models.BooleanField(default=False, verbose_name='Helmet'),
        ),
        migrations.AlterField(
            model_name='event',
            name='minor',
            field=models.BooleanField(default=False, verbose_name='Minor authorization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='safety_vest',
            field=models.BooleanField(default=False, verbose_name='Safety vest'),
        ),
    ]
