# Generated by Django 3.2.17 on 2023-05-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20230506_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_subscriber',
            field=models.PositiveIntegerField(default=1, verbose_name='Max number of subscribe'),
            preserve_default=False,
        ),
    ]
