# Generated by Django 3.2.17 on 2023-05-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bicycle_type',
            field=models.CharField(blank=True, choices=[('1', 'Electric'), ('2', 'Fatbike'), ('3', 'Mountain'), ('4', 'Gravel'), ('5', 'Hybrid'), ('6', 'Urban')], default='6', max_length=5, verbose_name='Choose a type of bicycle:'),
        ),
        migrations.AlterField(
            model_name='event',
            name='moto_type',
            field=models.CharField(blank=True, choices=[('1', 'The supermotards'), ('2', 'Sports'), ('3', 'Trails'), ('4', 'Roadsters'), ('5', 'Road'), ('6', '125 cm3'), ('7', 'Basics')], default='7', max_length=5, verbose_name='Choose a type of motobike:'),
        ),
    ]
