# Generated by Django 3.2.17 on 2023-05-07 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20230507_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.date(2023, 5, 7), verbose_name='Event date'),
            preserve_default=False,
        ),
    ]
