# Generated by Django 3.2.17 on 2023-05-08 15:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone'),
        ),
    ]
