# Generated by Django 3.2.17 on 2023-05-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='phone',
        ),
    ]
