# Generated by Django 3.2.18 on 2023-05-26 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(validators=[django.core.validators.RegexValidator(message="Date should be in the format 'YYYY-MM-DD'.", regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
    ]
