# Generated by Django 3.2.18 on 2023-05-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20230529_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='club',
        ),
        migrations.RemoveField(
            model_name='event',
            name='shop',
        ),
    ]
