# Generated by Django 3.2.17 on 2023-03-14 11:01

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the club')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('thumbnail', models.ImageField(default='default.png', upload_to='clubs/%Y/%M/', verbose_name='Logo')),
                ('description', tinymce.models.HTMLField()),
                ('location', mapbox_location_field.models.LocationField(map_attrs={}, verbose_name='Location')),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(map_id='map', verbose_name='Address')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone number')),
                ('site', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
