# Generated by Django 3.2.17 on 2023-05-05 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20230505_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='date',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='club',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
