# Generated by Django 3.2.17 on 2023-05-06 19:54

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'style': 'mapbox://styles/mapbox/streets-v12'}, verbose_name='Location'),
        ),
    ]
