# Generated by Django 3.2.17 on 2023-05-06 19:55

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_club_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={}, verbose_name='Location'),
        ),
    ]
