# Generated by Django 3.2.17 on 2023-05-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
