# Generated by Django 3.2.17 on 2023-05-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='created',
            new_name='date',
        ),
    ]
