# Generated by Django 3.2.17 on 2023-05-05 07:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_created_shop_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
