# Generated by Django 3.2.17 on 2023-05-05 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='date',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='shop',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
